behaviors:
  Pong:
    trainer_type: sac
    hyperparameters:
      batch_size: 1000
      buffer_size: 100000
      learning_rate: 0.0002
      buffer_init_steps: 5000
      learning_rate_schedule: constant
      steps_per_update: 40
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5000
    max_steps: 80000000
    time_horizon: 1000
    summary_freq: 20000
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 50000
      swap_steps: 10000
      team_change: 200000
